name: dverge
channels:
  - defaults
dependencies:
  - python=3.7
  - pip=19.1.1
  - pip:
    - torch==1.4.0
    - torchvision==0.5.0
    - tensorboard==2.2.0
    - advertorch==0.2.2
    - tqdm==4.46.1
    - pandas==1.0.1